server:
  port: 8080
spring:
  application:
    name: cards
  profiles:
    active: qa
  config:
    import: "optional:configserver:http://localhost:8071/"
  rabbitmq: #docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.12-management
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"