server:
  port: 8081
spring:
  application:
    name: cards
  profiles:
    active: qa
  config:
    import: "optional:configserver:http://localhost:8071/"
#  rabbitmq: #docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.12-management
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registryWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cards"
    description: "Vikram Singh cards microservice"
    version: "1.1.0"

logging:
  level:
    com:
      vikramsingh:
        cards: DEBUG