services:
  accounts:
    image: "vikramthory/accounts:0.0.1"
    container_name: accounts-service
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vikramthoryms
  loans:
    image: "vikramthory/loans:0.0.1"
    container_name: loans-service
    ports:
      - "8090:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vikramthoryms
  cards:
    image: "vikramthory/cards:0.0.1"
    container_name: cards-service
    ports:
      - "9000:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - vikramthoryms
networks:
  vikramthoryms:
    driver: "bridge"