server:
  port: 8080
spring:
  application:
    name: loans
  profiles:
    active: qa
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"